-- MySQL Script generated by MySQL Workbench
-- Wed Nov 29 03:51:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gc_ap_sc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gc_ap_sc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gc_ap_sc` DEFAULT CHARACTER SET utf8 ;
USE `gc_ap_sc` ;

-- -----------------------------------------------------
-- Table `gc_ap_sc`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`role` (
  `id` TINYINT(1) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gc_ap_sc`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `role_id` TINYINT(1) UNSIGNED NOT NULL,
  `options` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_user_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `gc_ap_sc`.`role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gc_ap_sc`.`auth_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`auth_token` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `selector` CHAR(12) NOT NULL,
  `token` CHAR(64) NOT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  `expires` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_auth_token_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_auth_token_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `gc_ap_sc`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gc_ap_sc`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`category` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `parent_id` INT(11) UNSIGNED NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gc_ap_sc`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`product` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `cross_code` VARCHAR(255) NOT NULL,
  `firm` VARCHAR(255) NOT NULL,
  `orig_code` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `characteristic` VARCHAR(255) NOT NULL,
  `category_id` INT(11) UNSIGNED NOT NULL,
  `price` INT(11) UNSIGNED NOT NULL,
  `quantity` INT(11) UNSIGNED NOT NULL,
  `place` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `gc_ap_sc`.`category` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gc_ap_sc`.`balance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`balance` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `balance_date` DATETIME NOT NULL,
  `product_id` INT(11) UNSIGNED NOT NULL,
  `income_price` INT(11) UNSIGNED NOT NULL,
  `income_quantity` INT(11) UNSIGNED NOT NULL,
  `income_sum` INT(11) UNSIGNED NOT NULL,
  `outcome_price` INT(11) UNSIGNED NOT NULL,
  `outcome_quantity` INT(11) UNSIGNED NOT NULL,
  `outcome_sum` INT(11) UNSIGNED NOT NULL,
  `remainder` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_balance_product_idx` (`product_id` ASC),
  CONSTRAINT `fk_balance_product`
    FOREIGN KEY (`product_id`)
    REFERENCES `gc_ap_sc`.`product` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gc_ap_sc`.`currency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gc_ap_sc`.`currency` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `value` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
